### PR TITLE
Encoding length detection improvment

### PR DESCRIPTION
**Pull request by BoiteAWeb**
Use mb_strlen() if exists

### CODE REVIEW

**Comment by jdevalk** [comment]
Wouldn't it be nicer to just do:

```php
if ( ! function_exists( 'mb_strlen' ) ) {
  function mb_strlen( $string ) {
    return strlen( $string ); 
  }
}
```

And leave the other code intact?

**Comment by BoiteAWeb** [comment]
No, if you can't use mb_strlen, don't use mb_strlen or people/dev/coders will trust you that you're actually using mb_strlen.

**Comment by jdevalk** [comment]
Yeah.. Thinking. WP Core, as of 4.2, [does a fallback](https://github.com/WordPress/WordPress/blob/974ca19e36dd71e7c506de05ca862d29a134e6dc/wp-includes/compat.php#L99).

**Comment by BoiteAWeb** [comment]
This one is correct cause it mimics the real one, but in a PHP way.

**Comment by BoiteAWeb** [comment]
Using my patch with "function_exists( 'mb_strlen' )" will use the WP one, which is fine.

**Comment by BoiteAWeb** [comment]
the _mb_strlen from WP is available since 3.7

**Comment by jdevalk** [comment]
So 

```php
if ( ! function_exists( 'mb_strlen' ) ) {
  function mb_strlen( $string ) {
    return _mb_strlen( $string ); 
  }
}
```

_would_ actually work in 3.7+, which I'm fine with :)

**Comment by BoiteAWeb** [comment]
In 3.7+ you don't have to do anything since mb_strlen() already exists, indeed. and don't use _mb_strlen without checking the existence too. it exists only since 3.7, what about a 3.6 running your plugin, is that forbidden? If yes, did you warn the user and deactivate the plugin?

**Comment by BoiteAWeb** [comment]
now you can check if WP 3.7+ and use mb_strlen 
or check fct exists mb_strlen, 
which is barely the same.

**Comment by jdevalk** [comment]
In that case :) merging.

**Comment by BoiteAWeb** [comment]
You're welcome :)

**Pull request merged**
